# Site default meta keywords
#keywords: site, wide, default, keywords

menu:
  Home: /
  About: /about
  Archives: /archives

widgets:
- search
- about
- category
#- tagcloud
#- recent_posts
#- tag

# For use with tagcloud or tag widgets
# - only tags >= to tag_minium are shown
tag_minium: 3

twitter_id:
facebook_id:
linkedin_id:
github_id:
google_plus_id: 100169331366580286164

addthis:
  enable: true
  pubid: ra-5371a9c6342c7855
  twitter: true
  facebook: true

about:
  title: Über Philipp Keller
  content:
  - image: /images/philipp.jpg
    image_alt: Philipp
    description: Ich bin verheiratet und habe 2 Kinder (6 und 3 Jahre alt). Ich habe an der ETH Informatik studiert und arbeite bei local.ch.
  - image: /images/john-piper.jpg
    image_alt: John Piper
    description: "Seit 1998 bin ich Christ, mich begeistert bibeltreue Theologie gepaart mit Begeisterung und Authentizität. Ich bin grosser Fan von <a href=\"http://www.desiringgod.org/\">John Piper</a>"
  - image: /images/philipp-gitarre.jpg
    image_alt: Philipp mit Gitarre
    description: "Ich selber bin Anbetungsleiter in der <a href=\"http://www.pfimi-kloten.ch/\">Pfingstgemeinde Kloten</a>"

google_analytics: UA-53694-9
rss:

disqus_shortname: philippkeller
