# Site default meta keywords
#keywords: site, wide, default, keywords

menu:
  Home: /
  Archives: /archives

highlight:
  style: solarized_dark
  enable: true
  line_number: true

widgets:
- search
- category
- tagcloud
- tag
#- about
#- subscribe_mailchimp
#- noteworthy

marked:
  gfm: true
  tables: true

polymer:
- github-card


# For use with tagcloud or tag widgets
# - only tags >= to tag_minium are shown
tag_minium: 3

twitter_id:
facebook_id:
linkedin_id:
github_id:
google_plus_id: 

# add "share post to facebook/twitter" buttons to your post
# you need to get a pubid from addthis to use it

# addthis:
#   enable: true
#   pubid: ...
#   twitter: true
#   facebook: true

# this is the about section, it apprears top right

about:
  title: About Dennis
  content:
    #  - image: http://img.forumfr.com/cafe/20041204_TopicJohnDoe.jpg
    #    image_alt: John
    #    description: I'm a hacker from around the world

noteworthy_title:
noteworthy:
#  - url: /bibeln/
#    title: Deutsche Bibelübersetzungen

# Mailchimp:
# 
# to set up mailing over Mailchimp create a campaign based on RSS
#
# to get those ids, go to Mailchimp and go to
# lists -> embedded -> naked
# see copy/paste onto site:

mailchimp:
  # inside <form action="…">
  post_action:
  # inside <input type="text" name="…" tabindex="-1" value="">
  field_name:

google_analytics:
rss:

disqus_shortname:
