# Site default meta keywords
#keywords: site, wide, default, keywords

menu:
  Home: /
  About: /about
  Archives: /archives

widgets:
- search
- category
- tagcloud
#- recent_posts
#- tag

# For use with tagcloud or tag widgets
# - only tags >= to tag_minium are shown
tag_minium: 3

twitter_id:
facebook_id:
linkedin_id:
github_id:
google_plus_id: 100169331366580286164

addthis:
  enable: true
  pubid: ra-5371a9c6342c7855
  twitter: true
  facebook: true

google_analytics: UA-53694-9
rss:

disqus_shortname: philippkeller
